// js/utils/export.js - PDF export utility

const ExportUtility = {
  /**
   * Generate PDF report
   */
  async generateReport(data) {
    if (!data) {
      throw new Error('No data provided for export');
    }

    // Validate export data
    const validation = Validators.validateExportData(data);
    if (!validation.valid) {
      throw new Error(`Cannot export: ${validation.errors.join(', ')}`);
    }

    try {
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();

      // Set document properties
      doc.setProperties({
        title: 'Venture Assessment Report',
        subject: `Assessment of ${data.company.company_overview?.name || 'Company'}`,
        author: 'Venture Assessment Platform',
        keywords: 'venture, assessment, team, competitive, market, ip risk, intellectual property',
        creator: 'Venture Assessment Platform'
      });

      // Add pages
      this.addTitlePage(doc, data);
      doc.addPage();
      this.addExecutiveSummary(doc, data);
      if (data.team) {
        doc.addPage();
        this.addTeamAssessment(doc, data);
      }
      doc.addPage();
      this.addCompetitiveAssessment(doc, data);
      doc.addPage();
      this.addMarketAssessment(doc, data);
      doc.addPage();
      this.addIpRiskAssessment(doc, data);
      
      // Add appendix with full data
      doc.addPage();
      this.addAppendixCover(doc);
      doc.addPage();
      this.addCompanyDetails(doc, data.company);
      if (data.team) {
        doc.addPage();
        this.addTeamDetails(doc, data.team);
      }
      doc.addPage();
      this.addCompetitiveDetails(doc, data.competitive);
      doc.addPage();
      this.addMarketDetails(doc, data.market);
      doc.addPage();
      this.addIpRiskDetails(doc, data.iprisk);

      // Generate filename
      const timestamp = new Date().toISOString().split('T')[0];
      const companyName = data.company.company_overview?.name || 'company';
      const filename = `assessment_${companyName.toLowerCase().replace(/\s+/g, '_')}_${timestamp}.pdf`;

      // Save the PDF
      doc.save(filename);

      return filename;
    } catch (error) {
      console.error('Export failed:', error);
      throw error;
    }
  },

  /**
   * Add title page
   */
  addTitlePage(doc, data) {
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  // Title
  doc.setFontSize(28);
  doc.setFont(undefined, 'bold');
  doc.text('Venture Assessment Report', pageWidth / 2, 60, { align: 'center' });

  // Company name
  doc.setFontSize(20);
  doc.setFont(undefined, 'normal');
  const companyName = data.company.company_overview?.name || 'Unknown Company';
  doc.text(companyName, pageWidth / 2, 80, { align: 'center' });

  // SCA Name
  const scaName = document.getElementById('scaName')?.value || 'Not specified';
  doc.setFontSize(12);
  doc.text(`Assessed by: ${scaName}`, pageWidth / 2, 95, { align: 'center' });

  // Date
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(date, pageWidth / 2, 105, { align: 'center' });

  // Rest of the method continues...

    // Scores box
    const boxY = 120;
    doc.setDrawColor(102, 126, 234);
    doc.setLineWidth(1);
    doc.rect(30, boxY, pageWidth - 60, 80);

    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Assessment Results', pageWidth / 2, boxY + 20, { align: 'center' });

      // Dimension scores
      doc.setFontSize(12);
      doc.setFont(undefined, 'normal');
      
      const formatScore = (score) => (score === undefined || score === null ? '-' : `${score}/9`);
      const columns = [
        {
          title: 'Team Strength',
          ai: formatScore(data.team?.score),
          user: formatScore(data.team?.userScore)
        },
        {
          title: 'Funding Readiness',
          ai: formatScore(data.funding?.score),
          user: formatScore(data.funding?.userScore)
        },
        {
          title: 'Competitive Risk',
          ai: formatScore(data.competitive.assessment.score),
          user: formatScore(data.competitive.userScore)
        },
        {
          title: 'Market Opportunity',
          ai: formatScore(data.market.scoring.score),
          user: formatScore(data.market.userScore)
        },
        {
          title: 'IP Risk',
          ai: formatScore(data.iprisk.score),
          user: formatScore(data.iprisk.userScore)
        }
      ];

      const columnWidth = (pageWidth - 90) / columns.length;

      columns.forEach((col, index) => {
        const x = 45 + index * columnWidth;
        doc.text(col.title, x, boxY + 40);
        doc.text(`AI Score: ${col.ai}`, x, boxY + 50);
        doc.text(`User Score: ${col.user}`, x, boxY + 60);
      });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(128);
    doc.text('Generated by Venture Assessment Platform', pageWidth / 2, pageHeight - 20, { align: 'center' });
  },

  /**
   * Add executive summary
   */
  addExecutiveSummary(doc, data) {
    const pageWidth = doc.internal.pageSize.width;
    let y = 30;

    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('Executive Summary', 20, y);
    y += 15;

    // Company overview
    doc.setFontSize(14);
    doc.text('Company Overview', 20, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    const overview = data.company.company_overview;
    const lines = doc.splitTextToSize(
      overview.company_description || overview.mission_statement || 'No description available',
      pageWidth - 40
    );
    doc.text(lines, 20, y);
    y += lines.length * 5 + 10;

    // Key metrics
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Key Metrics', 20, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    
    // Competitive metrics
    const competitive = data.competitive.formatted;
    doc.text(`• Total Competitors: ${competitive.totalCompetitors}`, 25, y);
    y += 7;
    doc.text(`• Competitive Intensity: ${Formatters.competitiveIntensity(competitive.competitiveIntensity)}`, 25, y);
    y += 7;
    doc.text(`• Market Leaders: ${competitive.marketLeaders.length}`, 25, y);
    y += 10;

    // Funding metrics
    const funding = data.funding?.formatted || {};
    const fundingConfidence = typeof funding.confidence === 'number'
      ? Formatters.confidence(funding.confidence)
      : 'Not available';
    const totalPeerDeals = funding.totalPeerDeals ?? (funding.peerDeals ? funding.peerDeals.length : 0);
    doc.text(`• Prior Funding Secured: ${funding.hasPriorFunding ? 'Yes' : 'No'}`, 25, y);
    y += 7;
    doc.text(`• Funding Rounds Identified: ${funding.totalFundingRounds ?? 0}`, 25, y);
    y += 7;
    doc.text(`• Comparable Market Deals: ${totalPeerDeals}`, 25, y);
    y += 7;
    doc.text(`• Funding Data Confidence: ${fundingConfidence}`, 25, y);
    y += 10;

    // Market metrics
    const market = data.market.formatted;
    doc.text(`• Total Addressable Market: ${Formatters.currency(market.primaryMarket.tam)}`, 25, y);
    y += 7;
    doc.text(`• Growth Rate (CAGR): ${Formatters.percentage(market.primaryMarket.cagr)}`, 25, y);
    y += 7;
    doc.text(`• Market Category: ${Formatters.tamCategory(market.tamCategory)}`, 25, y);
    y += 7;

    const iprisk = data.iprisk.formatted;
    const ipRiskConfidence = iprisk.dataConfidence !== null && iprisk.dataConfidence !== undefined
      ? `${Math.round(iprisk.dataConfidence * 100)}%`
      : 'Unknown';
    doc.text(`• IP Risk Level: ${Formatters.titleCase(iprisk.riskLevel || 'Unknown')}`, 25, y);
    y += 7;
    doc.text(`• Unique Protectable Features: ${(iprisk.uniqueFeatures || []).length}`, 25, y);
    y += 7;
    doc.text(`• Top Patent Owners Reviewed: ${(iprisk.topOwners || []).length}`, 25, y);
    y += 7;
    doc.text(`• IP Data Confidence: ${ipRiskConfidence}`, 25, y);
    y += 15;

    // Assessment summary
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Assessment Summary', 20, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    const teamFormatted = data.team?.formatted || {};
    const teamComposition = teamFormatted.teamComposition || {};
    const teamMembersCount = teamComposition.total ?? (teamFormatted.members?.length ?? '-');
    const teamStrengthsText = (teamFormatted.strengths || []).slice(0, 2).join('; ') || 'Not specified';
    const teamGapsText = (teamFormatted.gaps || []).slice(0, 2).join('; ') || 'Not specified';
    const teamConfidence = teamFormatted.confidence !== undefined && teamFormatted.confidence !== null
      ? Formatters.confidence(teamFormatted.confidence)
      : 'Not available';

    doc.text(`�?� Team Size: ${teamMembersCount}`, 25, y);
    y += 7;
    doc.text(`�?� Technical Experts: ${teamComposition.technical ?? 0} | Business Leaders: ${teamComposition.business ?? 0}`, 25, y);
    y += 7;
    doc.text(`�?� Team Assessment Confidence: ${teamConfidence}`, 25, y);
    y += 7;

    const strengthLines = doc.splitTextToSize(`�?� Key Strengths: ${teamStrengthsText}`, pageWidth - 60);
    strengthLines.forEach(line => {
      doc.text(line, 25, y);
      y += 7;
    });

    const gapLines = doc.splitTextToSize(`�?� Key Gaps: ${teamGapsText}`, pageWidth - 60);
    gapLines.forEach(line => {
      doc.text(line, 25, y);
      y += 7;
    });
    y += 3;
    
    const fundingFormatted = data.funding?.formatted || {};
    const fundingConfidenceSummary = typeof fundingFormatted.confidence === 'number'
      ? Formatters.confidence(fundingFormatted.confidence)
      : 'Not available';
    const fundingSummaryLines = [
      `• Funding Rounds: ${fundingFormatted.totalFundingRounds ?? 0}`,
      `• Comparable Deals Reviewed: ${fundingFormatted.totalPeerDeals ?? (fundingFormatted.peerDeals ? fundingFormatted.peerDeals.length : 0)}`,
      `• Funding Confidence: ${fundingConfidenceSummary}`
    ];
    fundingSummaryLines.forEach(text => {
      const lines = doc.splitTextToSize(text, pageWidth - 60);
      lines.forEach(line => {
        doc.text(line, 25, y);
        y += 7;
      });
    });
    y += 3;

    const aiScores = [
      data.team?.score,
      data.funding?.score,
      data.competitive.assessment.score,
      data.market.scoring.score,
      data.iprisk.score
    ].filter(score => score !== undefined && score !== null);

    const userScores = [
      data.team?.userScore,
      data.funding?.userScore,
      data.competitive.userScore,
      data.market.userScore,
      data.iprisk.userScore
    ].filter(score => score !== undefined && score !== null);

    const avgAiScore = aiScores.length
      ? aiScores.reduce((sum, value) => sum + value, 0) / aiScores.length
      : null;
    const avgUserScore = userScores.length
      ? userScores.reduce((sum, value) => sum + value, 0) / userScores.length
      : null;
    
    doc.text(`Average AI Score: ${avgAiScore !== null ? `${avgAiScore.toFixed(1)}/9` : '-'}`, 25, y);
    y += 7;
    doc.text(`Average User Score: ${avgUserScore !== null ? `${avgUserScore.toFixed(1)}/9` : '-'}`, 25, y);
  },

  /**
   * Add team assessment page
   */
  addTeamAssessment(doc, data) {
    const pageWidth = doc.internal.pageSize.width;
    let y = 30;

    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('Team Assessment', 20, y);
    y += 15;

    if (!data.team) {
      doc.setFontSize(12);
      doc.setFont(undefined, 'normal');
      doc.text('Team assessment data not available.', 20, y);
      return;
    }

    const ensureSpace = (padding = 20) => {
      if (y > 280 - padding) {
        doc.addPage();
        y = 30;
      }
    };

    const team = data.team;
    const formatted = team.formatted || {};
    const composition = formatted.teamComposition || {};
    const members = formatted.members || [];
    const strengths = formatted.strengths || [];
    const gaps = formatted.gaps || [];
    const experiences = formatted.experiences || [];

    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`AI Score: ${team.score ?? '-'}/9`, 20, y);
    doc.text(`User Score: ${team.userScore ?? '-'}/9`, 90, y);
    y += 10;

    if (team.userJustification) {
      ensureSpace(30);
      doc.setFont(undefined, 'bold');
      doc.text('User Justification:', 20, y);
      y += 7;

      doc.setFont(undefined, 'normal');
      const justificationLines = doc.splitTextToSize(team.userJustification, pageWidth - 40);
      justificationLines.forEach(line => {
        ensureSpace(10);
        doc.text(line, 25, y);
        y += 6;
      });
      y += 4;
    }

    // Composition summary
    ensureSpace(35);
    doc.setFont(undefined, 'bold');
    doc.text('Team Composition', 20, y);
    y += 8;

    doc.setFont(undefined, 'normal');
    doc.text(`�?� Total Members: ${composition.total ?? members.length}`, 25, y);
    y += 6;
    doc.text(`�?� Technical Experts: ${composition.technical ?? 0}`, 25, y);
    y += 6;
    doc.text(`�?� Business Leaders: ${composition.business ?? 0}`, 25, y);
    y += 6;
    doc.text(`�?� Domain Experts: ${composition.domain ?? 0}`, 25, y);
    y += 10;

    const renderListSection = (title, items, maxItems = 5) => {
      ensureSpace(30);
      doc.setFont(undefined, 'bold');
      doc.text(title, 20, y);
      y += 8;

      doc.setFont(undefined, 'normal');
      if (!items || items.length === 0) {
        doc.text('�?� None noted.', 25, y);
        y += 6;
        return;
      }

      items.slice(0, maxItems).forEach(item => {
        const text = typeof item === 'string' ? item : JSON.stringify(item);
        const lines = doc.splitTextToSize(`�?� ${text}`, pageWidth - 45);
        lines.forEach(line => {
          ensureSpace(10);
          doc.text(line, 25, y);
          y += 6;
        });
      });

      if (items.length > maxItems) {
        doc.text(`...and ${items.length - maxItems} more`, 25, y);
        y += 6;
      }

      y += 4;
    };

    renderListSection('Key Strengths', strengths);
    renderListSection('Key Gaps', gaps);
    renderListSection('Relevant Experience Highlights', experiences, 6);

    // Key members
    ensureSpace(35);
    doc.setFont(undefined, 'bold');
    doc.text('Key Team Members', 20, y);
    y += 8;

    doc.setFont(undefined, 'normal');
    if (members.length === 0) {
      doc.text('�?� No team members listed.', 25, y);
      y += 6;
    } else {
      members.slice(0, 4).forEach(member => {
        ensureSpace(35);
        doc.setFont(undefined, 'bold');
        doc.text(member.name || 'Team Member', 25, y);
        y += 6;

        doc.setFont(undefined, 'normal');
        if (member.role_at_venture) {
          doc.text(`Role: ${member.role_at_venture}`, 25, y);
          y += 6;
        }

        const commercial = Array.isArray(member.commercialization_experience)
          ? member.commercialization_experience.map(exp => {
              if (typeof exp === 'string') return exp;
              const parts = [];
              if (exp.description) parts.push(exp.description);
              if (exp.company) parts.push(`(${exp.company})`);
              if (exp.outcome) parts.push(`- ${exp.outcome}`);
              return parts.join(' ');
            })
          : [];

        if (commercial.length > 0) {
          const lines = doc.splitTextToSize(`Commercial Experience: ${commercial[0]}`, pageWidth - 60);
          lines.forEach(line => {
            doc.text(line, 25, y);
            y += 5;
          });
        }

        if (member.education_history && member.education_history.length > 0) {
          const edu = member.education_history[0];
          const eduText = typeof edu === 'string'
            ? edu
            : `${edu.degree || ''} ${edu.institution ? ` - ${edu.institution}` : ''}`.trim();
          doc.text(`Education Highlight: ${eduText}`, 25, y);
          y += 5;
        }

        y += 6;
      });

      if (members.length > 4) {
        doc.text(`...and ${members.length - 4} additional team members`, 25, y);
        y += 6;
      }
    }

    // Sources
    const sources = formatted.sources || [];
    if (sources.length > 0) {
      ensureSpace(25);
      doc.setFont(undefined, 'bold');
      doc.text('Primary Sources', 20, y);
      y += 8;

      doc.setFont(undefined, 'normal');
      sources.slice(0, 5).forEach(source => {
        const lines = doc.splitTextToSize(`�?� ${source}`, pageWidth - 45);
        lines.forEach(line => {
          ensureSpace(10);
          doc.text(line, 25, y);
          y += 6;
        });
      });

      if (sources.length > 5) {
        doc.text(`...and ${sources.length - 5} more`, 25, y);
        y += 6;
      }
    }
  },

  /**
   * Add competitive assessment page
   */
  addCompetitiveAssessment(doc, data) {
    const pageWidth = doc.internal.pageSize.width;
    let y = 30;

    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('Competitive Risk Assessment', 20, y);
    y += 15;

    // Scores
    doc.setFontSize(12);
    doc.text(`AI Score: ${data.competitive.assessment.score}/9`, 20, y);
    doc.text(`User Score: ${data.competitive.userScore}/9`, 100, y);
    y += 10;

    // User justification
    if (data.competitive.userJustification) {
      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      doc.text('User Justification:', 20, y);
      y += 7;
      
      doc.setFont(undefined, 'normal');
      const justLines = doc.splitTextToSize(data.competitive.userJustification, pageWidth - 40);
      doc.text(justLines, 20, y);
      y += justLines.length * 5 + 10;
    }

    // AI reasoning
    doc.setFont(undefined, 'bold');
    doc.text('AI Assessment:', 20, y);
    y += 7;
    
    doc.setFont(undefined, 'normal');
    const aiLines = doc.splitTextToSize(
      data.competitive.assessment.score_justification || 'No justification provided',
      pageWidth - 40
    );
    doc.text(aiLines, 20, y);
    y += aiLines.length * 5 + 10;

    // Key risks
    if (y < 200) {
      doc.setFont(undefined, 'bold');
      doc.text('Key Risks:', 20, y);
      y += 7;
      
      doc.setFont(undefined, 'normal');
      const risks = data.competitive.assessment.key_risk_factors || [];
      risks.slice(0, 5).forEach(risk => {
        const riskLines = doc.splitTextToSize(`• ${risk}`, pageWidth - 45);
        doc.text(riskLines, 25, y);
        y += riskLines.length * 5 + 2;
      });
    }
  },

  /**
   * Add market assessment page
   */
  addMarketAssessment(doc, data) {
      const pageWidth = doc.internal.pageSize.width;
      let y = 30;
  
      doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('Market Opportunity Assessment', 20, y);
    y += 15;

    // Scores
    doc.setFontSize(12);
    doc.text(`AI Score: ${data.market.scoring.score}/9`, 20, y);
    doc.text(`User Score: ${data.market.userScore}/9`, 100, y);
    y += 10;

    // User justification
    if (data.market.userJustification) {
      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      doc.text('User Justification:', 20, y);
      y += 7;
      
      doc.setFont(undefined, 'normal');
      const justLines = doc.splitTextToSize(data.market.userJustification, pageWidth - 40);
      doc.text(justLines, 20, y);
      y += justLines.length * 5 + 10;
    }

    // AI reasoning
    doc.setFont(undefined, 'bold');
    doc.text('AI Assessment:', 20, y);
    y += 7;
    
    doc.setFont(undefined, 'normal');
    const aiLines = doc.splitTextToSize(
      data.market.scoring.justification?.summary || 'No justification provided',
      pageWidth - 40
    );
    doc.text(aiLines, 20, y);
    y += aiLines.length * 5 + 10;

    // Market details
    doc.setFont(undefined, 'bold');
    doc.text('Primary Market:', 20, y);
    y += 7;
    
    doc.setFont(undefined, 'normal');
    doc.text(`• TAM: ${Formatters.currency(data.market.analysis.primary_market.tam_usd)}`, 25, y);
    y += 7;
    doc.text(`• CAGR: ${Formatters.percentage(data.market.analysis.primary_market.cagr_percent)}`, 25, y);
    y += 7;
      doc.text(`• Description: ${data.market.analysis.primary_market.description}`, 25, y);
    },

    /**
     * Add IP risk assessment page
     */
    addIpRiskAssessment(doc, data) {
      const pageWidth = doc.internal.pageSize.width;
      let y = 30;

      const iprisk = data.iprisk;
      const formatted = iprisk.formatted || {};

      const ensureSpace = (padding = 20) => {
        if (y > 280 - padding) {
          doc.addPage();
          y = 30;
        }
      };

      const renderParagraph = (text) => {
        const content = text || 'No information provided.';
        const lines = doc.splitTextToSize(content, pageWidth - 40);
        lines.forEach(line => {
          ensureSpace(10);
          doc.text(line, 20, y);
          y += 5;
        });
        y += 5;
      };

      const renderList = (title, items) => {
        ensureSpace(20);
        doc.setFont(undefined, 'bold');
        doc.text(title, 20, y);
        y += 7;

        doc.setFont(undefined, 'normal');
        if (!items || items.length === 0) {
          doc.text('• None noted', 25, y);
          y += 6;
          return;
        }

        items.slice(0, 8).forEach(item => {
          const line = `• ${item}`;
          const lines = doc.splitTextToSize(line, pageWidth - 45);
          lines.forEach(textLine => {
            ensureSpace(10);
            doc.text(textLine, 25, y);
            y += 5;
          });
          y += 1;
        });
        y += 4;
      };

      doc.setFontSize(18);
      doc.setFont(undefined, 'bold');
      doc.text('IP Risk Assessment', 20, y);
      y += 15;

      doc.setFontSize(12);
      doc.setFont(undefined, 'normal');
      doc.text(`AI Score: ${iprisk.score ?? '-'}/9`, 20, y);
      doc.text(`User Score: ${iprisk.userScore ?? '-'}/9`, 100, y);
      y += 10;

      const riskLevel = Formatters.titleCase(formatted.riskLevel || 'Unknown');
      const dataConfidence = formatted.dataConfidence !== null && formatted.dataConfidence !== undefined
        ? `${Math.round(formatted.dataConfidence * 100)}%`
        : 'Unknown';
      doc.text(`Risk Level: ${riskLevel}`, 20, y);
      y += 7;
      doc.text(`Data Confidence: ${dataConfidence}`, 20, y);
      y += 10;

      if (iprisk.userJustification) {
        doc.setFont(undefined, 'bold');
        doc.text('User Justification:', 20, y);
        y += 7;
        doc.setFont(undefined, 'normal');
        renderParagraph(iprisk.userJustification);
      }

      doc.setFont(undefined, 'bold');
      doc.text('Company IP Position:', 20, y);
      y += 7;
      doc.setFont(undefined, 'normal');
      renderParagraph(formatted.companyIP?.description || formatted.companyCurrentIP?.description);

      doc.setFont(undefined, 'bold');
      doc.text('AI Assessment:', 20, y);
      y += 7;
      doc.setFont(undefined, 'normal');
      renderParagraph(formatted.riskAnalysis);

      renderList('Key IP Challenges', formatted.challenges || []);
      renderList('Unique Protectable Features', formatted.uniqueFeatures || []);
      renderList('Crowded Feature Areas', formatted.crowdedFeatures || []);
    },

  /**
   * Add appendix cover page
   */
  addAppendixCover(doc) {
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;

    doc.setFontSize(24);
    doc.setFont(undefined, 'bold');
    doc.text('APPENDIX', pageWidth / 2, pageHeight / 2 - 20, { align: 'center' });

    doc.setFontSize(14);
    doc.setFont(undefined, 'normal');
    doc.text('Detailed Analysis Data', pageWidth / 2, pageHeight / 2, { align: 'center' });
  },

  /**
   * Add company details to appendix
   */
  addCompanyDetails(doc, company) {
	  let y = 30;

	  doc.setFontSize(16);
	  doc.setFont(undefined, 'bold');
	  doc.text('Company Details', 20, y);
	  y += 12;

	  // Narrative Summary
	  doc.setFontSize(12);
	  doc.setFont(undefined, 'bold');
	  doc.text('Executive Summary', 20, y);
	  y += 8;
	  
	  doc.setFontSize(10);
	  doc.setFont(undefined, 'normal');
	  
	  const overview = company.company_overview || {};
	  const tech = company.technology || {};
	  const market = company.market_context || {};
	  
	  // Create narrative
	  const narrative = `${overview.name || 'The company'} is a ${overview.company_stage || 'technology'} stage company founded in ${overview.founded_year || 'recent years'}. ${overview.company_description || overview.mission_statement || 'The company focuses on innovative technology solutions.'}

	The company's core technology involves ${tech.core_technology || 'advanced solutions'} in the ${tech.technology_category || 'technology'} category. ${tech.technical_approach || ''}

	Operating in the ${market.industry || 'technology'} industry, the company addresses ${market.problem_addressed || 'market needs'} with a value proposition of ${market.value_proposition || 'innovative solutions'}.`;

	  const narrativeLines = doc.splitTextToSize(narrative, 160);
	  narrativeLines.forEach(line => {
		if (y > 270) {
		  doc.addPage();
		  y = 30;
		}
		doc.text(line, 20, y);
		y += 5;
	  });
	  
	  y += 10;
	  
	  // Detailed Table
	  if (y > 200) {
		doc.addPage();
		y = 30;
	  }
	  
	  doc.setFontSize(12);
	  doc.setFont(undefined, 'bold');
	  doc.text('Detailed Information', 20, y);
	  y += 8;
	  
	  // Create table format
	  const details = [
		['Company Name', overview.name || '-'],
		['Website', overview.website || '-'],
		['Founded', overview.founded_year || '-'],
		['Stage', overview.company_stage || '-'],
		['Employees', overview.employee_count || '-'],
		['Headquarters', overview.headquarters || '-'],
		['Industry', market.industry || '-'],
		['Business Model', market.business_model || '-']
	  ];
	  
	  doc.setFontSize(10);
	  details.forEach(([label, value]) => {
		if (y > 270) {
		  doc.addPage();
		  y = 30;
		}
		doc.setFont(undefined, 'bold');
		doc.text(label + ':', 20, y);
		doc.setFont(undefined, 'normal');
		const valueLines = doc.splitTextToSize(String(value), 120);
		doc.text(valueLines, 70, y);
		y += valueLines.length * 5 + 2;
	  });
  },

  /**
   * Add team details to appendix
   */
  addTeamDetails(doc, team) {
    const pageWidth = doc.internal.pageSize.width;
    let y = 30;

    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Team Details', 20, y);
    y += 12;

    if (!team) {
      doc.setFontSize(12);
      doc.setFont(undefined, 'normal');
      doc.text('Team data not available.', 20, y);
      return;
    }

    const formatted = team.formatted || {};
    const composition = formatted.teamComposition || {};
    const members = formatted.members || [];

    const ensureSpace = (padding = 25) => {
      if (y > 280 - padding) {
        doc.addPage();
        y = 30;
      }
    };

    const renderList = (title, items, formatter, emptyLabel, maxItems = null) => {
      ensureSpace(30);
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text(title, 20, y);
      y += 8;

      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      if (!items || items.length === 0) {
        doc.text(`�?� ${emptyLabel}`, 25, y);
        y += 6;
        return;
      }

      const entries = maxItems ? items.slice(0, maxItems) : items;
      entries.forEach(item => {
        const text = formatter(item);
        const lines = doc.splitTextToSize(`�?� ${text}`, pageWidth - 50);
        lines.forEach(line => {
          ensureSpace(10);
          doc.text(line, 25, y);
          y += 5;
        });
      });

      if (maxItems && items.length > maxItems) {
        doc.text(`...and ${items.length - maxItems} more`, 25, y);
        y += 6;
      }

      y += 4;
    };

    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('Summary', 20, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`�?� Total Members: ${composition.total ?? members.length}`, 25, y);
    y += 5;
    doc.text(`�?� Technical Experts: ${composition.technical ?? 0}`, 25, y);
    y += 5;
    doc.text(`�?� Business Leaders: ${composition.business ?? 0}`, 25, y);
    y += 5;
    doc.text(`�?� Domain Experts: ${composition.domain ?? 0}`, 25, y);
    y += 10;

    renderList(
      'Key Strengths',
      formatted.strengths || [],
      item => (typeof item === 'string' ? item : JSON.stringify(item)),
      'No strengths recorded',
      8
    );

    renderList(
      'Key Gaps',
      formatted.gaps || [],
      item => (typeof item === 'string' ? item : JSON.stringify(item)),
      'No gaps recorded',
      8
    );

    renderList(
      'Relevant Experience Highlights',
      formatted.experiences || [],
      item => (typeof item === 'string' ? item : JSON.stringify(item)),
      'No experience highlights recorded',
      10
    );

    const formatWork = (entry) => {
      if (typeof entry === 'string') return entry;
      const parts = [];
      if (entry.position) parts.push(entry.position);
      if (entry.company) parts.push(`@ ${entry.company}`);
      if (entry.duration) parts.push(`(${entry.duration})`);
      return parts.filter(Boolean).join(' ');
    };

    const formatEducation = (entry) => {
      if (typeof entry === 'string') return entry;
      const parts = [];
      if (entry.degree) parts.push(entry.degree);
      if (entry.institution) parts.push(`- ${entry.institution}`);
      if (entry.year) parts.push(`(${entry.year})`);
      return parts.filter(Boolean).join(' ');
    };

    const formatCommercial = (entry) => {
      if (typeof entry === 'string') return entry;
      const parts = [];
      if (entry.description) parts.push(entry.description);
      if (entry.company) parts.push(`(${entry.company})`);
      if (entry.outcome) parts.push(`- ${entry.outcome}`);
      return parts.filter(Boolean).join(' ');
    };

    const formatPublication = (entry) => {
      if (typeof entry === 'string') return entry;
      const parts = [];
      if (entry.title) parts.push(entry.title);
      if (entry.venue) parts.push(`- ${entry.venue}`);
      if (entry.year) parts.push(`(${entry.year})`);
      return parts.filter(Boolean).join(' ');
    };

    const formatAward = (entry) => {
      if (typeof entry === 'string') return entry;
      const parts = [];
      if (entry.award_name) parts.push(entry.award_name);
      if (entry.organization) parts.push(`- ${entry.organization}`);
      if (entry.year) parts.push(`(${entry.year})`);
      return parts.filter(Boolean).join(' ');
    };

    members.forEach(member => {
      ensureSpace(40);
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text(member.name || 'Team Member', 20, y);
      y += 8;

      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      if (member.role_at_venture) {
        doc.text(`Role: ${member.role_at_venture}`, 25, y);
        y += 6;
      }

      renderList(
        'Commercial Experience',
        member.commercialization_experience || [],
        formatCommercial,
        'No commercialization experience listed'
      );

      renderList(
        'Work History',
        member.work_history || [],
        formatWork,
        'No work history listed'
      );

      renderList(
        'Education',
        member.education_history || [],
        formatEducation,
        'No education history listed'
      );

      renderList(
        'Papers & Publications',
        member.papers_publications || [],
        formatPublication,
        'No publications listed'
      );

      renderList(
        'Awards & Recognition',
        member.awards_recognition || [],
        formatAward,
        'No awards listed'
      );

      y += 6;
    });

    const sources = formatted.sources || [];
    if (sources.length > 0) {
      ensureSpace(25);
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text('Sources', 20, y);
      y += 8;

      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      sources.forEach(source => {
        const lines = doc.splitTextToSize(`�?� ${source}`, pageWidth - 50);
        lines.forEach(line => {
          ensureSpace(10);
          doc.text(line, 25, y);
          y += 5;
        });
      });
    }
  },

  /**
   * Add competitive details to appendix
   */
  addCompetitiveDetails(doc, competitive) {
  let y = 30;

  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.text('Competitive Analysis Details', 20, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');

  // Add summary details first
  const details = [
    `Total Competitors: ${competitive.assessment.competitor_count.total}`,
    `Competitive Intensity: ${competitive.assessment.competitive_intensity}`,
    `Confidence Level: ${competitive.analysis.data_quality?.confidence_level || 'N/A'}`,
    '',
    'Market Leaders:',
    ...competitive.assessment.market_leaders.slice(0, 5).map(leader => `  • ${leader}`),
  ];

  details.forEach(line => {
    if (y > 270) {
      doc.addPage();
      y = 30;
    }
    doc.text(line, 20, y);
    y += 6;
  });

  // Add ALL competitors
  y += 10;
  if (y > 240) {
    doc.addPage();
    y = 30;
  }
  
  doc.setFont(undefined, 'bold');
  doc.text('All Identified Competitors:', 20, y);
  y += 8;
  
  doc.setFont(undefined, 'normal');
  const allCompetitors = competitive.analysis.competitors || [];
  
  allCompetitors.forEach((comp, index) => {
    if (y > 250) {
      doc.addPage();
      y = 30;
    }
    
    // Company name and size
    doc.setFont(undefined, 'bold');
    doc.text(`${index + 1}. ${comp.company_name || 'Unknown'}`, 25, y);
    doc.setFont(undefined, 'normal');
    doc.text(`(${comp.size_category || 'Unknown size'})`, 120, y);
    y += 6;
    
    // In addCompetitiveDetails method, update the competitor description section (around line 520):
	// Product/Description
	if (comp.product_description) {
	  const descLines = doc.splitTextToSize(comp.product_description, 150); // Reduced from 160
	  descLines.slice(0, 3).forEach(line => { // Show up to 3 lines
		if (y > 270) {
		  doc.addPage();
		  y = 30;
		}
		doc.text(line, 30, y);
		y += 4; // Reduced line spacing
	  });
	}
    y += 3;
  });

  // Add risk factors
  if (y > 220) {
    doc.addPage();
    y = 30;
  }
  
  y += 10;
  doc.setFont(undefined, 'bold');
  doc.text('Key Risk Factors:', 20, y);
  y += 8;
  doc.setFont(undefined, 'normal');
  
  competitive.assessment.key_risk_factors.forEach(risk => {
    if (y > 270) {
      doc.addPage();
      y = 30;
    }
    const riskLines = doc.splitTextToSize(`• ${risk}`, 170);
    riskLines.forEach(line => {
      doc.text(line, 25, y);
      y += 5;
    });
    y += 2;
  });
},

  /**
   * Add market details to appendix
   */
    addMarketDetails(doc, market) {
    let y = 30;
  
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
  doc.text('Market Analysis Details', 20, y);
  y += 12;

  // Primary market
  doc.setFontSize(12);
  doc.text('Primary Market', 20, y);
  y += 8;
  
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.text(`Description: ${market.analysis.primary_market.description}`, 25, y);
  y += 6;
  doc.text(`TAM: ${Formatters.currency(market.analysis.primary_market.tam_usd)}`, 25, y);
  y += 6;
  doc.text(`CAGR: ${Formatters.percentage(market.analysis.primary_market.cagr_percent)}`, 25, y);
  y += 10;

  // All market segments
  doc.setFont(undefined, 'bold');
  doc.text('All Market Segments Analyzed:', 20, y);
  y += 8;
  
  doc.setFont(undefined, 'normal');
  market.analysis.markets.forEach((mkt, index) => {
    if (y > 250) {
      doc.addPage();
      y = 30;
    }

    doc.setFont(undefined, 'bold');
    doc.text(`${index + 1}. ${mkt.description}`, 25, y);
    y += 6;
    
    doc.setFont(undefined, 'normal');
    doc.text(`  TAM: ${Formatters.currency(mkt.tam_current_usd)}`, 30, y);
    y += 5;
    doc.text(`  CAGR: ${Formatters.percentage(mkt.cagr_percent)}`, 30, y);
    y += 5;
    doc.text(`  Confidence: ${Formatters.confidence(mkt.confidence)}`, 30, y);
    y += 8;
  });

  // Market opportunities
  if (y > 220) {
    doc.addPage();
    y = 30;
  }
  
  y += 10;
  doc.setFont(undefined, 'bold');
  doc.text('Market Opportunities:', 20, y);
  y += 8;
  doc.setFont(undefined, 'normal');
  
  const opportunities = market.analysis.market_analysis?.opportunities || [];
  opportunities.forEach(opp => {
    if (y > 270) {
      doc.addPage();
      y = 30;
    }
      const oppLines = doc.splitTextToSize(`• ${opp}`, 170);
      oppLines.forEach(line => {
        doc.text(line, 25, y);
        y += 5;
      });
    y += 2;
  });
  },

  /**
   * Add IP risk details to appendix
   */
  addIpRiskDetails(doc, iprisk) {
    const pageWidth = doc.internal.pageSize.width;
    let y = 30;

    const formatted = iprisk.formatted || {};

    const ensureSpace = (padding = 20) => {
      if (y > 280 - padding) {
        doc.addPage();
        y = 30;
      }
    };

    const renderParagraphSection = (title, text) => {
      ensureSpace(25);
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text(title, 20, y);
      y += 8;

      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      const content = text || 'No information provided.';
      const lines = doc.splitTextToSize(content, pageWidth - 40);
      lines.forEach(line => {
        ensureSpace(10);
        doc.text(line, 20, y);
        y += 5;
      });
      y += 6;
    };

    const renderListSection = (title, items) => {
      ensureSpace(25);
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text(title, 20, y);
      y += 8;

      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      if (!items || items.length === 0) {
        doc.text('• None noted', 25, y);
        y += 6;
        return;
      }

      items.forEach(item => {
        const lines = doc.splitTextToSize(`• ${item}`, pageWidth - 45);
        lines.forEach(line => {
          ensureSpace(10);
          doc.text(line, 25, y);
          y += 5;
        });
        y += 3;
      });
      y += 4;
    };

    const formatPatentEntry = (patent) => {
      if (!patent) return 'Unknown patent';
      if (typeof patent === 'string') return patent;

      const parts = [];
      if (patent.patentID || patent.id) parts.push(patent.patentID || patent.id);
      if (patent.title) parts.push(patent.title);
      if (patent.year) parts.push(`(${patent.year})`);
      if (patent.assignee) parts.push(`- ${patent.assignee}`);
      return parts.filter(Boolean).join(' ');
    };

    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('IP Risk Analysis Details', 20, y);
    y += 12;

    renderParagraphSection(
      'Company IP Summary',
      formatted.companyIP?.description || formatted.companyCurrentIP?.description
    );

    const ownedPatents = (formatted.companyIP?.ownedPatents || []).map(formatPatentEntry);
    renderListSection('Company-Owned Patents', ownedPatents);

    renderListSection('Unique Protectable Features', formatted.uniqueFeatures || []);
    renderListSection('Crowded Feature Areas', formatted.crowdedFeatures || []);

    const topOwners = (formatted.topOwners || []).map(owner => {
      const count = owner.patentCount ?? 0;
      return `${owner.assignee || 'Unknown Assignee'} - ${count} patent${count === 1 ? '' : 's'}`;
    });
    renderListSection('Top Patent Owners', topOwners);

    const awardedPatents = (formatted.awardedPatents || []).map(formatPatentEntry);
    renderListSection('Granted Patents Reviewed', awardedPatents);

    const pendingPatents = (formatted.pendingPatents || []).map(formatPatentEntry);
    renderListSection('Pending Applications Reviewed', pendingPatents);

    const referencePatents = (formatted.relevantPatents || []).map(formatPatentEntry);
    renderListSection('Reference Patents Informing Risk Assessment', referencePatents);
  }
};

// Make available globally
window.ExportUtility = ExportUtility;
